version: "3.3"

# services:

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    network_mode: host
    volumes:
      - /container/postgresql/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
    network_mode: host
    volumes:
      - /container/pgadmin/data:/var/lib/pgadmin
    depends_on:
      - postgres

  redis1:
    image: redis:8
    container_name: redis1
    volumes:
     - /container/redis1/data:/data
     - /container/redis1/config:/usr/local/etc/redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    network_mode: host
